title: VizSec
email: simon.walton@oerc.ox.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  The IEEE Symposium on Visualization for Cyber Security (VizSec) is a forum that brings together researchers and practitioners from academia, government, and industry to address the needs of the cyber security community through new and insightful visualization and analysis techniques.
url: "http://vizsec.org"
twitter_username: vizsec
github_username:  vizsec

gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from

paginate: 5
paginate_path: "/news/page:num/"

sass:
  sass_dir: _sass
  style: compressed

markdown: kramdown

collections:
    - vizsecmeta

defaults:
  -
    scope:
      path: "" # empty string for all files
      type: "posts"
    values:
      layout: "post"
